Raise a customized nested exception when _zivid fails at import
The stacktrace from `import zivid` will now look like this:

Traceback (most recent call last):
  File "/tmp/env/lib/python3.7/site-packages/_zivid/__init__.py", line 3, in <module>
    from _zivid._zivid import (  # pylint: disable=import-error,no-name-in-module
ImportError: libZividCore.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/env/lib/python3.7/site-packages/zivid/__init__.py", line 8, in <module>
    from zivid.application import (
  File "/tmp/env/lib/python3.7/site-packages/zivid/application.py", line 2, in <module>
    import _zivid
  File "/tmp/env/lib/python3.7/site-packages/_zivid/__init__.py", line 23, in <module>
    ) from ex
ImportError: Failed to import the Zivid Python C-module, please check that:
 - Zivid SDK is installed
 - Zivid SDK version is matching the Zivid Python version
 - Zivid SDK libraries location is in PATH