Bump python dependencies
Without this commit the CI is broken, the error we got was
```
ERROR: Not able to automatically detect 'cl.exe' version
ERROR: Unable to find a working compiler
WARN: Remotes registry file missing, creating default one in C:\Users\runneradmin\.conan\remotes.json
ERROR: eigen/3.3.9: Cannot load recipe.
Error loading conanfile at 'C:\Users\runneradmin\.conan\data\eigen\3.3.9\_\_\export\conanfile.py': Current Conan version (1.40.3) does not satisfy the defined one (>=1.43.0).
```

By bumping the conan version this issue is now fixed.

(cherry picked from commit e58e5ae7b88ea87d7158bf57165807d02f0aaa61)